name: Go API CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Install dependencies
      run: go mod tidy

    - name: Run Tests
      env:
        DB_USER: testuser
        DB_PASSWORD: testpassword
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: testdb
      run: go test -v ./...

  deploy:
    name: Deploy para o GCP
    needs: test-and-build 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # 🚨 Só faz deploy se for na branch master

    steps:
      - name: Deploy para o Google Cloud VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            # Entra na pasta do projeto
            cd ~/api_auth_go
            
            # Baixa o código mais recente do GitHub
            git pull origin master
            
            # Reconstrói a API e sobe os containers em background
            sudo docker compose up --build -d
            
            # Limpa imagens antigas do Docker para poupar espaço no Free Tier
            sudo docker image prune -f